spring:
  application:
    name: coupon-service
  cloud:
    client:
      hostname: localhost
    gateway:
      discovery:
        locator:
          lower-case-service-id: true
          enabled: true
  jackson:
    default-property-inclusion: NON_NULL
  data:
    mongodb:
      uri: mongodb+srv://user:user@dealscoupons.otkgf.mongodb.net/test
      database: deal
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher


server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka
  instance:
    hostname: localhost
    preferIpAddress: true
    intance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${server.port}

springdoc:
  swagger-ui:
    path: /coupon-service-swagger.html
  operationsSorter: method


jwt.secret: dealsandcouponsecret